'use client';

import { useState } from 'react';
import Sidebar from '@/components/Sidebar';

const workspaceItems = [
  { id: 1, name: 'Project Alpha Report.pdf', type: 'document', date: '2024-01-15', size: '2.4 MB' },
  { id: 2, name: 'Data Analysis Script.py', type: 'code', date: '2024-01-14', size: '15 KB' },
  { id: 3, name: 'Meeting Notes.md', type: 'document', date: '2024-01-13', size: '8 KB' },
  { id: 4, name: 'Screenshot_2024-01-12.png', type: 'image', date: '2024-01-12', size: '1.2 MB' },
  { id: 5, name: 'Email Draft - Client.txt', type: 'text', date: '2024-01-11', size: '3 KB' },
];

export default function WorkspacePage() {
  const [filter, setFilter] = useState('all');

  return (
    <div className="h-screen flex">
      <Sidebar />
      
      <div className="flex-1 p-8 overflow-y-auto">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl font-bold mb-2 neon-text-cyan">💼 Workspace</h1>
          <p className="text-gray-400 mb-8">View and manage all files generated by Xeno</p>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
            <div className="glass-card p-4 card-hover">
              <div className="text-3xl mb-2">📄</div>
              <div className="text-2xl font-bold">24</div>
              <div className="text-sm text-gray-400">Total Files</div>
            </div>
            <div className="glass-card p-4 card-hover">
              <div className="text-3xl mb-2">💻</div>
              <div className="text-2xl font-bold">8</div>
              <div className="text-sm text-gray-400">Code Files</div>
            </div>
            <div className="glass-card p-4 card-hover">
              <div className="text-3xl mb-2">📊</div>
              <div className="text-2xl font-bold">12</div>
              <div className="text-sm text-gray-400">Documents</div>
            </div>
            <div className="glass-card p-4 card-hover">
              <div className="text-3xl mb-2">🖼️</div>
              <div className="text-2xl font-bold">4</div>
              <div className="text-sm text-gray-400">Images</div>
            </div>
          </div>

          {/* Filters */}
          <div className="flex gap-4 mb-6">
            {['all', 'document', 'code', 'image', 'text'].map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-4 py-2 rounded-lg transition-all ${
                  filter === f
                    ? 'bg-gradient-to-r from-cyan-600 to-purple-600 text-white'
                    : 'glass-card hover:bg-white hover:bg-opacity-10'
                }`}
              >
                {f.charAt(0).toUpperCase() + f.slice(1)}
              </button>
            ))}
          </div>

          {/* File List */}
          <div className="glass-card overflow-hidden">
            <table className="w-full">
              <thead className="bg-white bg-opacity-5">
                <tr>
                  <th className="text-left p-4">Name</th>
                  <th className="text-left p-4">Type</th>
                  <th className="text-left p-4">Date</th>
                  <th className="text-left p-4">Size</th>
                  <th className="text-right p-4">Actions</th>
                </tr>
              </thead>
              <tbody>
                {workspaceItems.map((item) => (
                  <tr key={item.id} className="border-t border-white border-opacity-5 hover:bg-white hover:bg-opacity-5 transition-colors">
                    <td className="p-4">
                      <div className="flex items-center gap-3">
                        <span className="text-2xl">
                          {item.type === 'document' ? '📄' :
                           item.type === 'code' ? '💻' :
                           item.type === 'image' ? '🖼️' : '📝'}
                        </span>
                        <span>{item.name}</span>
                      </div>
                    </td>
                    <td className="p-4">
                      <span className="px-2 py-1 bg-white bg-opacity-10 rounded text-sm capitalize">
                        {item.type}
                      </span>
                    </td>
                    <td className="p-4 text-gray-400">{item.date}</td>
                    <td className="p-4 text-gray-400">{item.size}</td>
                    <td className="p-4 text-right">
                      <button className="px-3 py-1 bg-cyan-600 hover:bg-cyan-700 rounded text-sm mr-2">
                        View
                      </button>
                      <button className="px-3 py-1 bg-purple-600 hover:bg-purple-700 rounded text-sm">
                        Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
